title: "My Portfolio"
description: "Showcasing my projects and experience"
theme: jekyll-theme-hacker
permalink: /:categories/:title
url: "https://repocz.github.io"
author: "Mauricio S." 
# Navigation menu
header_pages:
  - index.md
  - projects.md
  - resume.md
  - contact.md
